// Lista de países con código ISO alpha-2 (para flagcdn), prefijo telefónico y
// nombre en español. Usada por el selector de teléfono (PhoneInput).
// `code` en minúscula → https://flagcdn.com/w40/{code}.png

export type Country = { code: string; dial: string; name: string };

export const COUNTRIES: Country[] = [
  { code: "es", dial: "+34", name: "España" },
  { code: "af", dial: "+93", name: "Afganistán" },
  { code: "al", dial: "+355", name: "Albania" },
  { code: "de", dial: "+49", name: "Alemania" },
  { code: "ad", dial: "+376", name: "Andorra" },
  { code: "ao", dial: "+244", name: "Angola" },
  { code: "ai", dial: "+1", name: "Anguila" },
  { code: "ag", dial: "+1", name: "Antigua y Barbuda" },
  { code: "sa", dial: "+966", name: "Arabia Saudita" },
  { code: "dz", dial: "+213", name: "Argelia" },
  { code: "ar", dial: "+54", name: "Argentina" },
  { code: "am", dial: "+374", name: "Armenia" },
  { code: "aw", dial: "+297", name: "Aruba" },
  { code: "au", dial: "+61", name: "Australia" },
  { code: "at", dial: "+43", name: "Austria" },
  { code: "az", dial: "+994", name: "Azerbaiyán" },
  { code: "bs", dial: "+1", name: "Bahamas" },
  { code: "bh", dial: "+973", name: "Baréin" },
  { code: "bd", dial: "+880", name: "Bangladés" },
  { code: "bb", dial: "+1", name: "Barbados" },
  { code: "be", dial: "+32", name: "Bélgica" },
  { code: "bz", dial: "+501", name: "Belice" },
  { code: "bj", dial: "+229", name: "Benín" },
  { code: "bm", dial: "+1", name: "Bermudas" },
  { code: "by", dial: "+375", name: "Bielorrusia" },
  { code: "bo", dial: "+591", name: "Bolivia" },
  { code: "ba", dial: "+387", name: "Bosnia y Herzegovina" },
  { code: "bw", dial: "+267", name: "Botsuana" },
  { code: "br", dial: "+55", name: "Brasil" },
  { code: "bn", dial: "+673", name: "Brunéi" },
  { code: "bg", dial: "+359", name: "Bulgaria" },
  { code: "bf", dial: "+226", name: "Burkina Faso" },
  { code: "bi", dial: "+257", name: "Burundi" },
  { code: "bt", dial: "+975", name: "Bután" },
  { code: "cv", dial: "+238", name: "Cabo Verde" },
  { code: "kh", dial: "+855", name: "Camboya" },
  { code: "cm", dial: "+237", name: "Camerún" },
  { code: "ca", dial: "+1", name: "Canadá" },
  { code: "qa", dial: "+974", name: "Catar" },
  { code: "td", dial: "+235", name: "Chad" },
  { code: "cl", dial: "+56", name: "Chile" },
  { code: "cn", dial: "+86", name: "China" },
  { code: "cy", dial: "+357", name: "Chipre" },
  { code: "co", dial: "+57", name: "Colombia" },
  { code: "km", dial: "+269", name: "Comoras" },
  { code: "cg", dial: "+242", name: "Congo" },
  { code: "cd", dial: "+243", name: "Congo (RD)" },
  { code: "kr", dial: "+82", name: "Corea del Sur" },
  { code: "kp", dial: "+850", name: "Corea del Norte" },
  { code: "ci", dial: "+225", name: "Costa de Marfil" },
  { code: "cr", dial: "+506", name: "Costa Rica" },
  { code: "hr", dial: "+385", name: "Croacia" },
  { code: "cu", dial: "+53", name: "Cuba" },
  { code: "cw", dial: "+599", name: "Curazao" },
  { code: "dk", dial: "+45", name: "Dinamarca" },
  { code: "dm", dial: "+1", name: "Dominica" },
  { code: "ec", dial: "+593", name: "Ecuador" },
  { code: "eg", dial: "+20", name: "Egipto" },
  { code: "sv", dial: "+503", name: "El Salvador" },
  { code: "ae", dial: "+971", name: "Emiratos Árabes Unidos" },
  { code: "er", dial: "+291", name: "Eritrea" },
  { code: "sk", dial: "+421", name: "Eslovaquia" },
  { code: "si", dial: "+386", name: "Eslovenia" },
  { code: "us", dial: "+1", name: "Estados Unidos" },
  { code: "ee", dial: "+372", name: "Estonia" },
  { code: "et", dial: "+251", name: "Etiopía" },
  { code: "ph", dial: "+63", name: "Filipinas" },
  { code: "fi", dial: "+358", name: "Finlandia" },
  { code: "fj", dial: "+679", name: "Fiyi" },
  { code: "fr", dial: "+33", name: "Francia" },
  { code: "ga", dial: "+241", name: "Gabón" },
  { code: "gm", dial: "+220", name: "Gambia" },
  { code: "ge", dial: "+995", name: "Georgia" },
  { code: "gh", dial: "+233", name: "Ghana" },
  { code: "gi", dial: "+350", name: "Gibraltar" },
  { code: "gd", dial: "+1", name: "Granada" },
  { code: "gr", dial: "+30", name: "Grecia" },
  { code: "gl", dial: "+299", name: "Groenlandia" },
  { code: "gp", dial: "+590", name: "Guadalupe" },
  { code: "gu", dial: "+1", name: "Guam" },
  { code: "gt", dial: "+502", name: "Guatemala" },
  { code: "gf", dial: "+594", name: "Guayana Francesa" },
  { code: "gn", dial: "+224", name: "Guinea" },
  { code: "gq", dial: "+240", name: "Guinea Ecuatorial" },
  { code: "gw", dial: "+245", name: "Guinea-Bisáu" },
  { code: "gy", dial: "+592", name: "Guyana" },
  { code: "ht", dial: "+509", name: "Haití" },
  { code: "nl", dial: "+31", name: "Países Bajos" },
  { code: "hn", dial: "+504", name: "Honduras" },
  { code: "hk", dial: "+852", name: "Hong Kong" },
  { code: "hu", dial: "+36", name: "Hungría" },
  { code: "in", dial: "+91", name: "India" },
  { code: "id", dial: "+62", name: "Indonesia" },
  { code: "iq", dial: "+964", name: "Irak" },
  { code: "ir", dial: "+98", name: "Irán" },
  { code: "ie", dial: "+353", name: "Irlanda" },
  { code: "is", dial: "+354", name: "Islandia" },
  { code: "ky", dial: "+1", name: "Islas Caimán" },
  { code: "il", dial: "+972", name: "Israel" },
  { code: "it", dial: "+39", name: "Italia" },
  { code: "jm", dial: "+1", name: "Jamaica" },
  { code: "jp", dial: "+81", name: "Japón" },
  { code: "jo", dial: "+962", name: "Jordania" },
  { code: "kz", dial: "+7", name: "Kazajistán" },
  { code: "ke", dial: "+254", name: "Kenia" },
  { code: "kg", dial: "+996", name: "Kirguistán" },
  { code: "ki", dial: "+686", name: "Kiribati" },
  { code: "kw", dial: "+965", name: "Kuwait" },
  { code: "la", dial: "+856", name: "Laos" },
  { code: "ls", dial: "+266", name: "Lesoto" },
  { code: "lv", dial: "+371", name: "Letonia" },
  { code: "lb", dial: "+961", name: "Líbano" },
  { code: "lr", dial: "+231", name: "Liberia" },
  { code: "ly", dial: "+218", name: "Libia" },
  { code: "li", dial: "+423", name: "Liechtenstein" },
  { code: "lt", dial: "+370", name: "Lituania" },
  { code: "lu", dial: "+352", name: "Luxemburgo" },
  { code: "mo", dial: "+853", name: "Macao" },
  { code: "mk", dial: "+389", name: "Macedonia del Norte" },
  { code: "mg", dial: "+261", name: "Madagascar" },
  { code: "my", dial: "+60", name: "Malasia" },
  { code: "mw", dial: "+265", name: "Malaui" },
  { code: "mv", dial: "+960", name: "Maldivas" },
  { code: "ml", dial: "+223", name: "Malí" },
  { code: "mt", dial: "+356", name: "Malta" },
  { code: "ma", dial: "+212", name: "Marruecos" },
  { code: "mq", dial: "+596", name: "Martinica" },
  { code: "mu", dial: "+230", name: "Mauricio" },
  { code: "mr", dial: "+222", name: "Mauritania" },
  { code: "mx", dial: "+52", name: "México" },
  { code: "md", dial: "+373", name: "Moldavia" },
  { code: "mc", dial: "+377", name: "Mónaco" },
  { code: "mn", dial: "+976", name: "Mongolia" },
  { code: "me", dial: "+382", name: "Montenegro" },
  { code: "mz", dial: "+258", name: "Mozambique" },
  { code: "mm", dial: "+95", name: "Birmania" },
  { code: "na", dial: "+264", name: "Namibia" },
  { code: "np", dial: "+977", name: "Nepal" },
  { code: "ni", dial: "+505", name: "Nicaragua" },
  { code: "ne", dial: "+227", name: "Níger" },
  { code: "ng", dial: "+234", name: "Nigeria" },
  { code: "no", dial: "+47", name: "Noruega" },
  { code: "nz", dial: "+64", name: "Nueva Zelanda" },
  { code: "om", dial: "+968", name: "Omán" },
  { code: "pk", dial: "+92", name: "Pakistán" },
  { code: "pw", dial: "+680", name: "Palaos" },
  { code: "ps", dial: "+970", name: "Palestina" },
  { code: "pa", dial: "+507", name: "Panamá" },
  { code: "pg", dial: "+675", name: "Papúa Nueva Guinea" },
  { code: "py", dial: "+595", name: "Paraguay" },
  { code: "pe", dial: "+51", name: "Perú" },
  { code: "pf", dial: "+689", name: "Polinesia Francesa" },
  { code: "pl", dial: "+48", name: "Polonia" },
  { code: "pt", dial: "+351", name: "Portugal" },
  { code: "pr", dial: "+1", name: "Puerto Rico" },
  { code: "gb", dial: "+44", name: "Reino Unido" },
  { code: "cf", dial: "+236", name: "República Centroafricana" },
  { code: "cz", dial: "+420", name: "República Checa" },
  { code: "do", dial: "+1", name: "República Dominicana" },
  { code: "re", dial: "+262", name: "Reunión" },
  { code: "rw", dial: "+250", name: "Ruanda" },
  { code: "ro", dial: "+40", name: "Rumanía" },
  { code: "ru", dial: "+7", name: "Rusia" },
  { code: "ws", dial: "+685", name: "Samoa" },
  { code: "kn", dial: "+1", name: "San Cristóbal y Nieves" },
  { code: "sm", dial: "+378", name: "San Marino" },
  { code: "vc", dial: "+1", name: "San Vicente y las Granadinas" },
  { code: "lc", dial: "+1", name: "Santa Lucía" },
  { code: "st", dial: "+239", name: "Santo Tomé y Príncipe" },
  { code: "sn", dial: "+221", name: "Senegal" },
  { code: "rs", dial: "+381", name: "Serbia" },
  { code: "sc", dial: "+248", name: "Seychelles" },
  { code: "sl", dial: "+232", name: "Sierra Leona" },
  { code: "sg", dial: "+65", name: "Singapur" },
  { code: "sy", dial: "+963", name: "Siria" },
  { code: "so", dial: "+252", name: "Somalia" },
  { code: "lk", dial: "+94", name: "Sri Lanka" },
  { code: "za", dial: "+27", name: "Sudáfrica" },
  { code: "sd", dial: "+249", name: "Sudán" },
  { code: "ss", dial: "+211", name: "Sudán del Sur" },
  { code: "se", dial: "+46", name: "Suecia" },
  { code: "ch", dial: "+41", name: "Suiza" },
  { code: "sr", dial: "+597", name: "Surinam" },
  { code: "th", dial: "+66", name: "Tailandia" },
  { code: "tw", dial: "+886", name: "Taiwán" },
  { code: "tz", dial: "+255", name: "Tanzania" },
  { code: "tj", dial: "+992", name: "Tayikistán" },
  { code: "tg", dial: "+228", name: "Togo" },
  { code: "to", dial: "+676", name: "Tonga" },
  { code: "tt", dial: "+1", name: "Trinidad y Tobago" },
  { code: "tn", dial: "+216", name: "Túnez" },
  { code: "tm", dial: "+993", name: "Turkmenistán" },
  { code: "tr", dial: "+90", name: "Turquía" },
  { code: "tv", dial: "+688", name: "Tuvalu" },
  { code: "ua", dial: "+380", name: "Ucrania" },
  { code: "ug", dial: "+256", name: "Uganda" },
  { code: "uy", dial: "+598", name: "Uruguay" },
  { code: "uz", dial: "+998", name: "Uzbekistán" },
  { code: "vu", dial: "+678", name: "Vanuatu" },
  { code: "va", dial: "+39", name: "Ciudad del Vaticano" },
  { code: "ve", dial: "+58", name: "Venezuela" },
  { code: "vn", dial: "+84", name: "Vietnam" },
  { code: "ye", dial: "+967", name: "Yemen" },
  { code: "dj", dial: "+253", name: "Yibuti" },
  { code: "zm", dial: "+260", name: "Zambia" },
  { code: "zw", dial: "+263", name: "Zimbabue" },
];

/** PNG real de la bandera (no emoji — se ve igual en Windows, Mac y móvil). */
export const flagUrl = (code: string) => `https://flagcdn.com/w40/${code}.png`;

/** Detecta el país a partir de un teléfono guardado; el prefijo más largo gana. */
export function parsePhone(value: string): { country: Country; number: string } {
  const v = (value ?? "").trim();
  const byLen = [...COUNTRIES].sort((a, b) => b.dial.length - a.dial.length);
  for (const c of byLen) {
    if (v.startsWith(c.dial)) return { country: c, number: v.slice(c.dial.length).trim() };
  }
  return { country: COUNTRIES[0], number: v };
}
