/**
 * Principales ciudades de España, para sugerir como opciones preestablecidas en
 * los campos de ciudad (p. ej. la disponibilidad del técnico). Se usan en un
 * <datalist>: el usuario ve las sugerencias pero puede escribir cualquier otra.
 * Orden aproximado por población (las más comunes primero).
 */
export const SPAIN_CITIES: string[] = [
  "Madrid",
  "Barcelona",
  "Valencia",
  "Sevilla",
  "Zaragoza",
  "Málaga",
  "Murcia",
  "Palma",
  "Las Palmas de Gran Canaria",
  "Bilbao",
  "Alicante",
  "Córdoba",
  "Valladolid",
  "Vigo",
  "Gijón",
  "L'Hospitalet de Llobregat",
  "Vitoria-Gasteiz",
  "A Coruña",
  "Granada",
  "Elche",
  "Oviedo",
  "Santa Cruz de Tenerife",
  "Badalona",
  "Cartagena",
  "Terrassa",
  "Jerez de la Frontera",
  "Sabadell",
  "Móstoles",
  "Alcalá de Henares",
  "Pamplona",
  "Almería",
  "San Sebastián",
  "Santander",
  "Castellón de la Plana",
  "Burgos",
  "Albacete",
  "Getafe",
  "Salamanca",
  "Logroño",
  "Huelva",
  "Marbella",
  "Lleida",
  "Tarragona",
  "León",
  "Cádiz",
  "Girona",
  "Ourense",
  "Toledo",
  "Cáceres",
  "Badajoz",
  "Mérida",
];
